name: flutter_url_shortener
description: This is a package that using bitly API service for generate shorten url. They could begin with the bit.ly domain or your own custom branded short domain (BSD)
version: 2.0.0
homepage: https://github.com/HadesPTIT/flutter_url_shortener

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: