name: flutter_url_shortener
description: A URL shortener built with Flutter using bitly API service
version: 1.0.0
homepage: https://github.com/HadesPTIT/flutter_url_shortener

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: